format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$character"""

[directory]
format = "[ $path]($style) "
style = "blue bold"

[character]
success_symbol = "\n[󰘍](purple)"
error_symbol = "\n[󰘍](red)"
vicmd_symbol = "\n[❮](green)"

[git_branch]
format = "[ $branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
